### ISSUE TITLE
Don't see download button. 

### ISSUE THREAD

**Issue by MindlessGonzo** [realcoloride/TwitterDL#6]
Installed, refresh, but the download button does not show up anywhere. Attached is a sample tweet of what I'm seeing. I'm using Tampermonkey and the most recent Google Chrome.
![5ede02bfb22c89590f04adf45f67a86b](https://github.com/realcoloride/TwitterDL/assets/101928782/df23adbc-f7d9-425b-bee7-37c44eccef62)

**Comment by realcoloride** [comment]
Hey there, download button work only on attachments that are videos or gifs. For photos, use right click > save as...

Otherwise if you still cannot see anything, please try to update the script to the latest version that recently added support for the x.com domain migration (version `1.1.2`). if you still need to use twitter.com to access the website, use version `1.1.1`.

**Comment by MindlessGonzo** [comment]
I thank you for clarifying on photos. However, I am on the latest, 1.1.2, and sadly still don't see it on the videos and gifs like you said.

**Comment by realcoloride** [comment]
Are you on the x.com or twitter.com domain?

**Comment by MindlessGonzo** [comment]
x.com

**Comment by MindlessGonzo** [comment]
Nevermind, turns out my bookmark was outdated, so a slight tweak to the URL has fixed the issue.

**Comment by realcoloride** [comment]
Is the issue resolved then?

**Comment by MindlessGonzo** [comment]
I guess so. I'm closing this ticket.
